version: '3.8'

services:
  postgresdb:
    build:
      context: ./store/DB
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./store
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb

  frontend:
    build:
      context: ./store/UI
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend






